name: Purge Cache
on:
  issues:
    types:
      - labeled
      - unlabeled
      - edited
jobs:
  deploy:
    name: Checkout and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache
        run: |
          curl -H "github_token: ${GITHUB_TOKEN}" "https://english-notes.jser.workers.dev/_increment_version"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
