name: Deploy on labeled/unlabeled issue
on:
  issues:
    types:
      - labeled
      - unlabeled
jobs:
  deploy:
    name: Checkout and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get BUILD_DATE
        id: date
        run: echo "::set-output name=BUILD_DATE::$(date '+%a, %d %b %Y %H:%M:%S GMT')"
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Worker
        if: github.event.label.name == 'public'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          publish: false
          preCommands: |
            wrangler build --env=production
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
      - name: Create Cache
        run: |
          echo "warm"
#          curl -D - -s -o /dev/null https://waka.dev
#          curl -D - -s -o /dev/null https://waka.dev/archive
#          curl -D - -s -o /dev/null https://waka.dev/feed.xml
