name: Deploy on push
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Checkout and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Get BUILD_DATE
        id: date
        run: echo "::set-output name=BUILD_DATE::$(date '+%a, %d %b %Y %H:%M:%S GMT')"
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          preCommands: |
            wrangler build --env=production
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
